### PR TITLE
Install ScriptDom dependency when it doesnt exist on host machine

### LINKED ISSUE #21: ScriptDom Not Found
Application fails when Microsoft.SqlServer.TransactSql.ScriptDom not already installed on host system.

### PR DESCRIPTION
**Pull request by nathan-boyd**
resolves #21

### CODE REVIEW

File: scripts/install/install.js [hunk 1]
```diff
@@ -1,2 +1,8 @@
 var fs = require('fs')
-fs.createReadStream('scripts/install/tsqllint').pipe(fs.createWriteStream(`${process.env.APPDATA}/npm/tsqllint`))
\ No newline at end of file
+const execSync = require('child_process').execSync;
+
+// calls powershell script to install missing dependencies
+execSync(`call ${process.env.APPDATA}/npm/node_modules/tsqllint/scripts/install/install-dependencies.cmd`);
```
Comment (dougwilson) [inline scripts/install/install.js]: `execSync` doesn't exist in Node.js 0.10 (only noted since that's what the base image comes installed with). LGTM if you're OK with that. May not be an issue if the default install has a broken PATH anyway, so a new install would do it good.

Comment (nathan-boyd) [inline scripts/install/install.js]: good note on the missing lib, i didn't realize that. if we weren't telling people to upgrade anyway, as you mentioned, I would revisit.
