### PR TITLE
Fix bug with MultiTableAliasRule and CTE

### LINKED ISSUE #9: CTE's used with derived table asking for aliasing.
When using a derived table with a common table expression inside, the linter asks for the common table expression to be aliased with default lintrc. This error disappears if you remove the Group clause.
This is the error: 
`Test.sql(25,20): error multi-table-alias : Unaliased table found in multi table joins.`

Test.sql
```SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

WITH CommonTableExpression (Foo, Bar)
AS (
	SELECT FooBars.Foo,
			FooCars.Bar
	FROM dbo.FooBars AS FooBars WITH (NOLOCK)
	LEFT JOIN dbo.FooCars AS FooCars
			ON Foobars.Foo = FooCars.Foo
)

SELECT
JoinedTable.Foo,
JoinedTable.Bar,
JoinedTable.Secret
FROM (
		SELECT
			CommonTableExpression.Foo,
			CommonTableExpression.Bar,
			CoolTable.Secret
		FROM dbo.CoolTable AS CoolTable WITH (NOLOCK)
		INNER JOIN CommonTableExpression    --multi-table-alias error here
			ON CommonTableExpression.Foo = CoolTable.Foo
		WHERE CoolTable.Secret < 5
) AS JoinedTable
GROUP BY JoinedTable.Foo,
JoinedTable.Bar,
JoinedTable.Secret;
```

### PR DESCRIPTION
**Pull request by nathan-boyd**
Scripts containing common table expressions were being
flagged as violating the Multi Table Alias rule.

* Add new CTE Rulevisitor to capture CTE Names
* Pass List of CTE Names to Table Alias Visitor

Resolves #9

### CODE REVIEW

File: TSQLLINT_LIB/Rules/MultiTableAliasRule.cs [hunk 1]
```diff
@@ -50,14 +70,21 @@ public override void Visit(JoinTableReference node)
...
-            public ChildTableAliasVisitor(Action<TSqlFragment> errorCallback)
+            public ChildTableAliasVisitor(Action<TSqlFragment> errorCallback, List<string> cteNames)
             {
+                CteNames = cteNames;
                 ChildCallback = errorCallback;
             }
 
             public override void Visit(NamedTableReference node)
             {
+                if(CteNames.Contains(node.SchemaObject.BaseIdentifier.Value))
```
Comment (dougwilson) [inline TSQLLINT_LIB/Rules/MultiTableAliasRule.cs]: If you're just creating a lookup, use `HashSet<T>` instead of `List<T>`.

Comment (nathan-boyd) [inline TSQLLINT_LIB/Rules/MultiTableAliasRule.cs]: good call
